### PR TITLE
Make the containers' names depend on project-name

### LINKED ISSUE #49: Make the containers' names depend on project-name
## Problem Statement

**Description**: When running the `npx create-soroban-dapp@latest` or `npm create soroban-dapp@latest` script for multiple projects, users encounter an error when attempting to run containers from those multiple projects simultaneously. This issue arises because the containers share the same names, leading to conflicts.
Error message when running containers in multiple projects:
```
Recreating soroban-preview ... 
stellar is up-to-date

ERROR: for soroban-preview  'ContainerConfig'

ERROR: for soroban-preview  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[48270] Failed to execute script docker-compose
```

**Impact of the Problem**: This conflict prevents developers from running multiple instances of the project simultaneously, which can significantly hinder productivity, especially in environments where multiple projects are being developed and tested concurrently.

## Proposed Solution

**Overview**: Modify the container naming convention in the create-soroban-dapp script to include the project name as a suffix. This will ensure that each project's containers have unique names, allowing them to run simultaneously without conflicts.

**Detailed Explanation**: Update the Docker Compose configuration within the `create-soroban-dapp` script to dynamically generate container names based on the project name. This could involve appending or prepending the project name to the container names (e.g., soroban-preview-projectname).

## Acceptance Criteria

**Specific Requirements:**
- Containers should be named with a unique identifier based on the project name.
-  The script should run without errors when multiple projects are executed 
-  No regression issues should be introduced in the naming convention or container functionality.

**Test Cases:**
- [ ] Verify that containers from different projects have unique names and can run simultaneously without 
- [ ] Test the script with multiple projects to ensure that the naming convention works as expected.
- [ ] Check `run.sh` script

## Technical Details

**Implementation Notes**: Modify the Docker Compose configuration within the create-soroban-dapp script to include a variable for the project name. This variable should be used to generate container names dynamically.

Dependencies: The project name should be passed as a command-line argument when the script is executed.

## Impact Analysis

Impact on Existing Features: This change will primarily impact the naming of containers. Care should be taken to ensure that any tooling or scripts dependent on container names are updated accordingly.

### PR DESCRIPTION
**Pull request by Ugo-X**
fixes #49 

Configured the compose.yml file to use unique project ids to differentiate projects

### CODE REVIEW

**Comment by MattPoblete** [comment]
Please, update the README.md  to proper usage

**Comment by Ugo-X** [comment]
> Please, update the README.md to proper usage

done ser

**Review by MattPoblete — APPROVED** [review]

**Comment by MattPoblete** [comment]
@chopan123 Ready to merge!

**Comment by Ugo-X** [comment]
> @chopan123 Ready to merge!

Alright🎉

**Pull request merged**
